Assistant view
ded8393/boh_app pull request #25
Opened 2023-10-23 20:45 UTC by ded8393

2023-10-24 07:50 UTC, flying-sheep commented on src/front/data/aspect/glass.png
This seems to be a blurry, smaller version with different borders compared to all others

2023-10-24 07:51 UTC, flying-sheep commented on src/front/data/aspect/soul.png
This is also a smaller version compared to the others, but maybe there just isn’t a big version (as the soul cards don’t show this icon themselves)

2023-10-24 12:34 UTC, ded8393 commented on src/front/data/aspect/soul.png
there is no larger image in the data

2023-10-25 12:04 UTC, flying-sheep requested changes
Looking good!

2023-10-25 12:04 UTC, flying-sheep commented on src/front/routes/Items.tsx
> +    }
you can do above:

```ts
type Principle = (typeof principles)[number]
```

and then:

```suggestion
    filters?: {
        known?: boolean
        aspect?: string
    } & { [principle: Principle]?: boolean }
```

2023-10-25 12:04 UTC, flying-sheep commented on src/front/routes/Items.tsx
> +    principles.forEach((principle) => {
never `forEach`, use `const filteredState = ...` where `...` contains `map`, `flatMap`, `filter`, and/or `reduce` and if you really have to do things imperatively, use `for (const x of y)`

2023-10-25 12:04 UTC, flying-sheep commented on src/front/routes/Items.tsx
> +            <Stack direction={"row"}>
```suggestion
            <Stack direction="row">
```

2023-10-25 12:38 UTC, ded8393 commented on src/boh_app/models.py
> -            return [self.special_aspect, *base_aspects]
this will still be in the git history; cannot remain as is because the model has changed enough for it to be non-functional

2023-10-25 12:49 UTC, flying-sheep approved these changes

2023-10-25 13:09 UTC, merged